In [1]:
# Importing dependencies
import json
import pandas as pd
import datetime
from pprint import pprint

In [2]:
nyc_json = json.load(open("nyc_pop.json"))

In [3]:
pprint(nyc_json)

{'data': [['row-vbrb_jnkz-vuw5',
           '00000000-0000-0000-E27F-BC6726D6C609',
           0,
           1542139670,
           None,
           1542139670,
           None,
           '{ }',
           'Total Population',
           'NYC Total',
           '7891957',
           '100.00',
           '7781984',
           '100.00',
           '7894862',
           '100.00',
           '7071639',
           '100.00',
           '7322564',
           '100.00',
           '8008278',
           '100.00',
           '8242624',
           '100.00',
           '8550971',
           '100.00',
           '8821027',
           '100.00',
           '9025145',
           '100.00'],
          ['row-rnxf.sj9f.r58p',
           '00000000-0000-0000-1BF2-0D0B3D4E782C',
           0,
           1542139670,
           None,
           1542139670,
           None,
           '{ }',
           'Total Population',
           '   Bronx',
           '1451277',
           '18.39',
           '1424815',
           '18.31',
           '1471701',
           '18.64',
           '1168972',
           '16.53',
           '1203789',
           '16.44',
           '1332650',
           '16.64',
           '1385108',
           '16.80',
           '1446788',
           '16.92',
           '1518998',
           '17.22',
           '1579245',
           '17.50'],
          ['row-kyc8_6yie~84v5',
           '00000000-0000-0000-A141-E2F8916957BC',
           0,
           1542139670,
           None,
           1542139670,
           None,
           '{ }',
           'Total Population',
           '   Brooklyn',
           '2738175',
           '34.70',
           '2627319',
           '33.76',
           '2602012',
           '32.96',
           '2230936',
           '31.55',
           '2300664',
           '31.42',
           '2465326',
           '30.78',
           '2552911',
           '30.97',
           '2648452',
           '30.97',
           '2754009',
           '31.22',
           '2840525',
           '31.47'],
          ['row-wp9c-2pm3~5c8w',
           '00000000-0000-0000-594D-7A0F3015909E',
           0,
           1542139670,
           None,
           1542139670,
           None,
           '{ }',
           'Total Population',
           '   Manhattan',
           '1960101',
           '24.84',
           '1698281',
           '21.82',
           '1539233',
           '19.50',
           '1428285',
           '20.20',
           '1487536',
           '20.31',
           '1537195',
           '19.20',
           '1585873',
           '19.24',
           '1638281',
           '19.16',
           '1676720',
           '19.01',
           '1691617',
           '18.74'],
          ['row-fd8f.qeet_sshn',
           '00000000-0000-0000-01E0-634398F2A27D',
           0,
           1542139670,
           None,
           1542139670,
           None,
           '{ }',
           'Total Population',
           '   Queens',
           '1550849',
           '19.65',
           '1809578',
           '23.25',
           '1986473',
           '25.16',
           '1891325',
           '26.75',
           '1951598',
           '26.65',
           '2229379',
           '27.84',
           '2250002',
           '27.30',
           '2330295',
           '27.25',
           '2373551',
           '26.91',
           '2412649',
           '26.73'],
          ['row-8dku_dr5w.479v',
           '00000000-0000-0000-D818-C5AED1146314',
           0,
           1542139670,
           None,
           1542139670,
           None,
           '{ }',
           'Total Population',
           '   Staten Island',
           '191555',
           '2.43',
           '221991',
           '2.85',
           '295443',
           '3.74',
           '352121',
           '4.98',
           '378977',
           '5.18',
           '443728',
           '5.54',
           '468730',
           '5.69',
           '487155',
           '5.70',
           '497749',
           '5.64',
           '501109',
           '5.55']],
 'meta': {'view': {'approvals': [{'reviewedAt': 1398784583,
                                  'reviewedAutomatically': True,
                                  'state': 'approved',
                                  'submissionDetails': {'permissionType': 'READ'},
                                  'submissionId': 1064989,
                                  'submissionObject': 'public_audience_request',
                                  'submissionOutcome': 'change_audience',
                                  'submissionOutcomeApplication': {'failureCount': 0,
                                                                   'status': 'success'},
                                  'submittedAt': 1398784583,
                                  'submitter': {'displayName': 'NYC OpenData',
                                                'id': '5fuc-pqz2'},
                                  'targetAudience': 'public',
                                  'workflowId': 2285}],
                   'assetType': 'dataset',
                   'attribution': 'Department of City Planning (DCP)',
                   'averageRating': 0,
                   'category': 'City Government',
                   'clientContext': {'clientContextVariables': [],
                                     'inheritedVariables': {}},
                   'columns': [{'dataTypeName': 'meta_data',
                                'fieldName': ':sid',
                                'flags': ['hidden'],
                                'format': {},
                                'id': -1,
                                'name': 'sid',
                                'position': 0,
                                'renderTypeName': 'meta_data'},
                               {'dataTypeName': 'meta_data',
                                'fieldName': ':id',
                                'flags': ['hidden'],
                                'format': {},
                                'id': -1,
                                'name': 'id',
                                'position': 0,
                                'renderTypeName': 'meta_data'},
                               {'dataTypeName': 'meta_data',
                                'fieldName': ':position',
                                'flags': ['hidden'],
                                'format': {},
                                'id': -1,
                                'name': 'position',
                                'position': 0,
                                'renderTypeName': 'meta_data'},
                               {'dataTypeName': 'meta_data',
                                'fieldName': ':created_at',
                                'flags': ['hidden'],
                                'format': {},
                                'id': -1,
                                'name': 'created_at',
                                'position': 0,
                                'renderTypeName': 'meta_data'},
                               {'dataTypeName': 'meta_data',
                                'fieldName': ':created_meta',
                                'flags': ['hidden'],
                                'format': {},
                                'id': -1,
                                'name': 'created_meta',
                                'position': 0,
                                'renderTypeName': 'meta_data'},
                               {'dataTypeName': 'meta_data',
                                'fieldName': ':updated_at',
                                'flags': ['hidden'],
                                'format': {},
                                'id': -1,
                                'name': 'updated_at',
                                'position': 0,
                                'renderTypeName': 'meta_data'},
                               {'dataTypeName': 'meta_data',
                                'fieldName': ':updated_meta',
                                'flags': ['hidden'],
                                'format': {},
                                'id': -1,
                                'name': 'updated_meta',
                                'position': 0,
                                'renderTypeName': 'meta_data'},
                               {'dataTypeName': 'meta_data',
                                'fieldName': ':meta',
                                'flags': ['hidden'],
                                'format': {},
                                'id': -1,
                                'name': 'meta',
                                'position': 0,
                                'renderTypeName': 'meta_data'},
                               {'cachedContents': {'cardinality': '1',
                                                   'count': '6',
                                                   'largest': 'Total '
                                                              'Population',
                                                   'non_null': '6',
                                                   'null': '0',
                                                   'smallest': 'Total '
                                                               'Population',
                                                   'top': [{'count': '6',
                                                            'item': 'Total '
                                                                    'Population'}]},
                                'dataTypeName': 'text',
                                'fieldName': 'age_group',
                                'format': {},
                                'id': 145715398,
                                'name': 'Age Group',
                                'position': 1,
                                'renderTypeName': 'text',
                                'tableColumnId': 19456803,
                                'width': 208},
                               {'cachedContents': {'cardinality': '6',
                                                   'count': '6',
                                                   'largest': '   Staten '
                                                              'Island',
                                                   'non_null': '6',
                                                   'null': '0',
                                                   'smallest': '   Bronx',
                                                   'top': [{'count': '1',
                                                            'item': '   Staten '
                                                                    'Island'},
                                                           {'count': '1',
                                                            'item': '   '
                                                                    'Manhattan'},
                                                           {'count': '1',
                                                            'item': 'NYC '
                                                                    'Total'},
                                                           {'count': '1',
                                                            'item': '   '
                                                                    'Queens'},
                                                           {'count': '1',
                                                            'item': '   Bronx'},
                                                           {'count': '1',
                                                            'item': '   '
                                                                    'Brooklyn'}]},
                                'dataTypeName': 'text',
                                'fieldName': 'borough',
                                'format': {},
                                'id': 145715399,
                                'name': 'Borough',
                                'position': 2,
                                'renderTypeName': 'text',
                                'tableColumnId': 19456804,
                                'width': 184},
                               {'cachedContents': {'average': '2630652.333333333',
                                                   'cardinality': '6',
                                                   'count': '6',
                                                   'largest': '7891957',
                                                   'non_null': '6',
                                                   'null': '0',
                                                   'smallest': '191555',
                                                   'sum': '15783914',
                                                   'top': [{'count': '1',
                                                            'item': '1550849'},
                                                           {'count': '1',
                                                            'item': '1451277'},
                                                           {'count': '1',
                                                            'item': '7891957'},
                                                           {'count': '1',
                                                            'item': '1960101'},
                                                           {'count': '1',
                                                            'item': '191555'},
                                                           {'count': '1',
                                                            'item': '2738175'}]},
                                'dataTypeName': 'number',
                                'fieldName': '_1950',
                                'format': {},
                                'id': 145715400,
                                'name': '1950',
                                'position': 3,
                                'renderTypeName': 'number',
                                'tableColumnId': 19456805,
                                'width': 148},
                               {'cachedContents': {'average': '33.335',
                                                   'cardinality': '6',
                                                   'count': '6',
                                                   'largest': '100.00',
                                                   'non_null': '6',
                                                   'null': '0',
                                                   'smallest': '2.43',
                                                   'sum': '200.01',
                                                   'top': [{'count': '1',
                                                            'item': '2.43'},
                                                           {'count': '1',
                                                            'item': '34.70'},
                                                           {'count': '1',
                                                            'item': '19.65'},
                                                           {'count': '1',
                                                            'item': '18.39'},
                                                           {'count': '1',
                                                            'item': '24.84'},
                                                           {'count': '1',
                                                            'item': '100.00'}]},
                                'dataTypeName': 'number',
                                'fieldName': '_1950_boro_share_of_nyc_total',
                                'format': {'percentScale': '100',
                                           'precisionStyle': 'percentage',
                                           'view': 'percent_bar_and_text'},
                                'id': 145715401,
                                'name': '1950 - Boro share of NYC total',
                                'position': 4,
                                'renderTypeName': 'number',
                                'tableColumnId': 19456806,
                                'width': 460},
                               {'cachedContents': {'average': '2593994.666666667',
                                                   'cardinality': '6',
                                                   'count': '6',
                                                   'largest': '7781984',
                                                   'non_null': '6',
                                                   'null': '0',
                                                   'smallest': '221991',
                                                   'sum': '15563968',
                                                   'top': [{'count': '1',
                                                            'item': '1424815'},
                                                           {'count': '1',
                                                            'item': '2627319'},
                                                           {'count': '1',
                                                            'item': '7781984'},
                                                           {'count': '1',
                                                            'item': '1809578'},
                                                           {'count': '1',
                                                            'item': '221991'},
                                                           {'count': '1',
                                                            'item': '1698281'}]},
                                'dataTypeName': 'number',
                                'fieldName': '_1960',
                                'format': {},
                                'id': 145715402,
                                'name': '1960',
                                'position': 5,
                                'renderTypeName': 'number',
                                'tableColumnId': 19456807,
                                'width': 148},
                               {'cachedContents': {'average': '33.33166666666667',
                                                   'cardinality': '6',
                                                   'count': '6',
                                                   'largest': '100.00',
                                                   'non_null': '6',
                                                   'null': '0',
                                                   'smallest': '2.85',
                                                   'sum': '199.99',
                                                   'top': [{'count': '1',
                                                            'item': '2.85'},
                                                           {'count': '1',
                                                            'item': '23.25'},
                                                           {'count': '1',
                                                            'item': '21.82'},
                                                           {'count': '1',
                                                            'item': '33.76'},
                                                           {'count': '1',
                                                            'item': '100.00'},
                                                           {'count': '1',
                                                            'item': '18.31'}]},
                                'dataTypeName': 'number',
                                'fieldName': '_1960_boro_share_of_nyc_total',

In [4]:
nyc_pop_df = pd.DataFrame(nyc_json["data"], columns=[
  # Dropping
  "drop1","drop2","drop3","drop4","drop5","drop6","drop7","drop8","total_population",
  # Keeping
  "borough",
  # Dropping
  "1950","1950%","1960","1960%","1970","1970%","1980","1980%","1990","1990%",
  "2000","2000%","2010","2010%",
  # Keeping
  "2020","2020%",
  # Dropping
  "2030","2030%","2040","2040%"
])
drop_columns = [
  "total_population","drop1","drop2","drop3","drop4","drop5","drop6","drop7","drop8","1950","1950%","1960",
  "1960%","1970","1970%","1980","1980%","1990","1990%","2000","2000%","2010","2010%",
  "2030","2030%","2040","2040%"
]
nyc_pop_df = nyc_pop_df.drop(columns=drop_columns)
nyc_pop_df = nyc_pop_df.rename(columns={"2020":"total_population", "2020%":"pop_portion"})
nyc_pop_df['borough'] = nyc_pop_df['borough'].apply(lambda x: str.strip(x))

nyc_pop_df.to_csv("2020_nyc_pop_df.csv")

In [5]:
nyc_pop_df

         borough total_population pop_portion
0      NYC Total          8550971      100.00
1          Bronx          1446788       16.92
2       Brooklyn          2648452       30.97
3      Manhattan          1638281       19.16
4         Queens          2330295       27.25
5  Staten Island           487155        5.70